Corrected Grammatical errors
AvianNetwork/Avian pull request #159
Opened 2022-09-07 06:43 UTC by JunaidPeer

2022-09-07 16:22 UTC, alamshafil commented
Thank you for your work! I changed the branch from master to 4.1-dev to prevent any merge conflicts in the future. If you could, please resolve the conflicts for 4.1. If you are confused, tell me and I can try to fix the conflicts from my end.

2022-09-07 16:24 UTC, alamshafil requested changes
Fix merge conflicts

2022-09-07 16:24 UTC, alamshafil commented on README.md
> +A digital peer-to-peer network for the facilitation of asset transfer.
4.1 has this:
```Avian digital peer to peer network for the facilitation of asset transfer.```

2022-09-17 13:33 UTC, cdonnachie commented on README.md
> +A digital peer-to-peer network for the facilitation of asset transfer.
I have corrected the conficts.

2022-09-17 14:17 UTC, alamshafil approved these changes

2022-09-17 14:17 UTC, alamshafil commented
ACK

2022-09-17 14:17 UTC, merged